### PR TITLE
change navbar and padding logo

### PR DESCRIPTION
**Pull request by frvanco**

### CODE REVIEW

**Review by JulienDelemarle — APPROVED** [review]
updating ok

**Comment by LoicBrassart** [comment]
Solve conflicts before assigning me plz ^^

**Comment by GeorgesFORTRY** [comment]
We will change method

**Review by JulienDelemarle — APPROVED** [review]
solved conflicts

**Review by LoicBrassart — APPROVED** [review]
Saw no Evil

**Pull request merged**
