### PR TITLE
Quiz structure

### PR DESCRIPTION
**Pull request by GeorgesFORTRY**

### CODE REVIEW

**Review by JulienDelemarle — DISMISSED** [review]
everything's ok

**Review by LoicBrassart — DISMISSED** [review]
Nice job, congrats

**Comment by GeorgesFORTRY** [comment]
resolve merge conflict with sass

**Review by JulienDelemarle — DISMISSED** [review]
review ok

**Comment by LoicBrassart** [comment]
Please solve conflicts **before** assigning me ;-)

**Review by JulienDelemarle — APPROVED** [review]
review ok

**Comment by LoicBrassart** [comment]
Wtf, that's the smallest PR ever: +0-0 !
All your changes already passed in another PR I think... And that's **not** good >_<

**Comment by GeorgesFORTRY** [comment]
PR = 0

**Pull request closed without merging**
